// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package storage

import (
	"context"
)

const getLong = `-- name: GetLong :one
SELECT longn FROM ShortLong WHERE short = ?
`

func (q *Queries) GetLong(ctx context.Context, short string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLong, short)
	var longn string
	err := row.Scan(&longn)
	return longn, err
}

const setShort = `-- name: SetShort :exec
INSERT INTO ShortLong(short, longn) VALUES (?, ?)
`

type SetShortParams struct {
	Short string
	Longn string
}

func (q *Queries) SetShort(ctx context.Context, arg SetShortParams) error {
	_, err := q.db.ExecContext(ctx, setShort, arg.Short, arg.Longn)
	return err
}
